### ISSUE TITLE
The android app is not fully capable with diffrent language filters 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#201]
**Describe the bug**
The android app is not fully capable with diffrent language filters 

**To Reproduce**
1. Click the app icon
2. Authenticate it and get in
3. In the right top , the language filter will be available
4. Click it and slect specific language 

**Expected behavior**
All the feilds should be translated to the specific language selected, with out any glitch 

**Current behavior**
Not all feilds where translated , and few feilds where not supporting and glitching out

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/199716470-16d34b75-d176-40cd-80b9-f64818fe00e8.png)
![image](https://user-images.githubusercontent.com/102220709/199716501-d5263915-6a79-44d4-9ce0-dde51f7237b0.png)
![image](https://user-images.githubusercontent.com/102220709/199716518-ac0cb0ce-f2e3-4d79-9e17-9a551d5c461a.png)
![image](https://user-images.githubusercontent.com/102220709/199716538-2d851133-3575-4bc7-b74c-dc48b02661fc.png)
![image](https://user-images.githubusercontent.com/102220709/199716560-c3cdfaf3-522e-46df-ae53-3f38f0afd4f2.png)
![image](https://user-images.githubusercontent.com/102220709/199716581-5b073d80-655c-4a08-bfcd-35683cf92aa8.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/suites/8476299188/artifacts/376688868

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-beta.1-10-d68f577-feature_mosip-55-face-matching-newlogic_20221115_1441.apk
iOS: 0.4.1 (1)

**ISSUE IS STILL PRESENT**
@kyanthony @pmigueld

Devices:
iPhone 11 - iOS 16.1
Samsung Galaxy A23 - Android 12

**Screenshots**
![Screenshot_20221116-141204_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202099977-d99a934b-418c-4748-a2c9-c1a6eb23a5f0.jpg)

![Screenshot_20221116-141257_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202099993-ea4f9325-bbbd-408c-8de7-3ffb5f5efa29.jpg)

![Screenshot_20221116-141348_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202100043-e4a6103a-0ba7-429b-a67c-45d91eaba8f2.jpg)

![Screenshot_20221116-141425_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202100055-5705cfc1-bd18-4e7b-8921-01e483326b9b.jpg)

![Screenshot_20221116-141436_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202100068-0fa2236a-a525-4d65-8944-9435432a1089.jpg)

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-beta.1-10-d68f577-feature_mosip-55-face-matching-newlogic_20221115_1441.apk

**WORKS AS EXPECTED**
@kyanthony @pmigueld @danicaerediano

**Devices:**
Samsung Galaxy A23 - Android 12

**Screenshots**
![Screenshot_20221116-183314_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202158219-0e7b91d8-2f7f-4dac-8ecd-196e5830a8a2.jpg)
![Screenshot_20221116-183321_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202158234-e06e8d47-eb12-4c3e-9bbf-eeb6124e9d87.jpg)
![Screenshot_20221116-183344_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202158254-08a5785c-4b09-4d21-a3a4-80410a4c43e7.jpg)
![Screenshot_20221116-183400_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202158266-983e8990-6341-4db4-b661-787673685436.jpg)
![Screenshot_20221116-183423_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202158280-5c7bc510-33fa-48cd-9908-6bec91f16cbb.jpg)
![Screenshot_20221116-183449_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/202158320-ccf6ce26-b0e0-45ab-9fcf-672d67bcf7f1.jpg)

**Comment by jannahadlaon** [comment]
**Tested on:**
Android: QA4_io.mosip.residentapp-0.4.1-rc1-newlogic_20221123_1723.apk
iOS: inji 0.4.1 (3) (TestFlight)

**iOS build 0.4.1** cuts the texts on the following buttons when translated.
As for the error message during face matching, maybe we can change the following words to:
portrait -> larawan
accessory -> aksesorya

**Assigned back to dev**
@pmigueld @kyanthony @danicaerediano 

**Screenshots**
![IMG_2983](https://user-images.githubusercontent.com/102940764/203723987-2d7c3944-b2c9-4889-ab5b-a8690e8e6f96.png)
![Screenshot_20221124-152546_MOSIP Resident App](https://user-images.githubusercontent.com/102940764/203724005-4a1ce938-c914-4382-a35f-9529da3b5e8c.jpg)

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [QA4_io.mosip.residentapp-0.4.1-rc3-newlogic_20221205_0904.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc3/QA4_io.mosip.residentapp-0.4.1-rc3-newlogic_20221205_0904.apk)
iOS: Inji 0.4.1 (4)

**ISSUE IS STILL PRESENT in iOS** 
**Assign back to dev**
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. Share an ID
2. **See error** on `Tanggapin ang kahilingan at piliin ang ID` and `Tanggapin anf kahilingan at magpatunay` button
3. Select an ID and clicking on either `Tanggapin ang kahilingan at piliin ang ID` or `Tanggapin anf kahilingan at magpatunay`
4. **See error**


**Test devices:**
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1

**Screens
![IMG_3136](https://user-images.githubusercontent.com/102940764/205811230-7bed948e-1fc3-4ef1-86cd-077e0e3bd332.jpg)
hot**
![IMG_3135](https://user-images.githubusercontent.com/102940764/205811243-102872e2-d8b9-4846-9e76-38839115fce9.jpg)

**Comment by Anushree09-N** [comment]
@santhoshsunder It's an Android bug please verify and update the status accordingly.

**Comment by santhoshsunder** [comment]
Verified this issue in QA5 env, we are seeing lot of elements still in english, but the past where has those elements in arabic, but the both files use the same local files, iam attaching both APK's screenshots bellow, hense reopening this bug

**Screenshot :** 
New APK 
![image](https://user-images.githubusercontent.com/102220709/209089474-2ae2db20-aea2-4e09-9797-f8c0532f90fb.png)
![image](https://user-images.githubusercontent.com/102220709/209089552-1bbd5a1f-b1c7-458e-b322-79b333b54ade.png)

Old APK
![image](https://user-images.githubusercontent.com/102220709/209089600-4e8c1b01-29b6-47ac-9586-d3304903b8fa.png)

**Smartphone :**
Device: PIXEL 6
OS: Android 13
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net
APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by Anil-kumar-Majji** [comment]
@Anushree09-N @santhoshsunder The above issues were solved by adjusting all related language files in locals. I raised the respective PR and sent it. Recheck once the code was merged.

**Comment by damodarguru** [comment]
Verified this issue in qa-1201-b2 environment, we are seeing lot of elements still not converted to Inji supported language, I am attaching the screenshots and the device details below for reference, hence reopening this bug.
Screenshots: -
![image](https://user-images.githubusercontent.com/124761463/225624256-8f459146-bdf5-4681-9699-4f40002230e7.png)
![image](https://user-images.githubusercontent.com/124761463/225624289-94e35d0b-6f64-47b8-9625-e94e85dbeb7e.png)
![image](https://user-images.githubusercontent.com/124761463/225624371-80ee7918-a604-4c89-a19d-d0929687cd95.png)
![image](https://user-images.githubusercontent.com/124761463/225624452-85c0dfca-baa2-41d2-b4f5-45a57594d03c.png)
![image](https://user-images.githubusercontent.com/124761463/225624618-b55c3311-dc0a-4a87-855d-46d71d11d9ae.png)
![image](https://user-images.githubusercontent.com/124761463/225624674-75c905ba-8dd9-4601-b6e9-e5ad63ee2100.png)
![image](https://user-images.githubusercontent.com/124761463/225624794-1758b928-7b2c-4f1a-9d53-272d19d59ebf.png)
![image](https://user-images.githubusercontent.com/124761463/225624929-a8f77f5b-8b26-4a41-91b4-df7b631cc6cd.png)
Tested In: -
Device A: Redmi 7A
Android Version: 10
BLE version :4.2
Inji app link: https://github.com/mosip/inji/actions/runs/4376878070
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net

**Comment by Anil-kumar-Majji** [comment]
@Sujithbn @damodarguru  @Raginikrishnamurthy I solved this re-opened bug by fixing it in locals of languages JSON files and raised respective PR(#654)

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link of the bug on Jira: https://mosip.atlassian.net/browse/MOSIP-26835
