### ISSUE TITLE
In inji app still labels and button remained in english even after language switch

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#223]
**Describe the bug**
In inji app still labels and button remained in english even after language switch

**To Reproduce**

1. Unlock the app
2. click on language filter which is available in the right top corner in home page/profile section.
3. Choose any language ex: kan

**Current behavior**
Not all feilds where translated , and few feilds where not supporting and glitching out

**Expected behavior**
All labels and button should be converted to User selecting language.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/200543055-2e7cecff-695b-4522-add9-26b4a8a42311.png)
![image](https://user-images.githubusercontent.com/79500509/200543084-c7c5fddd-8525-4915-9d45-47d3b9a1aacb.png)
![image](https://user-images.githubusercontent.com/79500509/200543135-cabbfbaa-dcd1-48e7-b3a1-38f292cd5081.png)
![image](https://user-images.githubusercontent.com/79500509/200543176-206338f0-4254-4545-b04c-b5ff0cbec33b.png)
![image](https://user-images.githubusercontent.com/79500509/200543202-2cc28aa7-0389-4f0f-a173-1946e4eafb4b.png)
![image](https://user-images.githubusercontent.com/79500509/200543226-00dee92e-6b14-4605-8ae1-b6d1c846845c.png)
![image](https://user-images.githubusercontent.com/79500509/200543265-fcba8842-65ee-4a36-903e-71ae98bf8887.png)
![image](https://user-images.githubusercontent.com/79500509/200543306-8997bef5-a0fe-4f5b-82ba-43d40695f667.png)
![image](https://user-images.githubusercontent.com/79500509/200543355-ee8bd838-ba82-480a-b827-4fbf113aef4c.png)
![image](https://user-images.githubusercontent.com/79500509/200543384-ec1718b5-12c0-40bc-a06b-8924b9d772fc.png)
![image](https://user-images.githubusercontent.com/79500509/200543862-ee3ce8ab-6dcc-4d8e-bf19-683ee11c415c.png)

**Smartphone (please complete the following information):**
Device: iPhone7 & iPhone XR
OS: 15.4.1
Inji app version: 0.4.0 (16) in test flight
MOSIP Version: 1.2.1
MOSIP server: qa-121.mosip.net

**Additional context**
Issue registered in Android https://github.com/mosip/inji/issues/201

**Comment by danicaerediano** [comment]
@pmigueld tested and it is translated in the recent develop branch

**Comment by danicaerediano** [comment]
@jannahadlaon base on your recent comment: https://github.com/mosip/inji/issues/201#issuecomment-1326072899
this is fixed already

**Comment by jannahadlaon** [comment]
**Tested on**
Android: [QA4_io.mosip.residentapp-0.4.1-rc3-newlogic_20221205_0904.apk](https://github.com/idpass/inji/releases/download/0.4.1-rc3/QA4_io.mosip.residentapp-0.4.1-rc3-newlogic_20221205_0904.apk)
iOS: Inji 0.4.1 (4)

**ISSUE IS STILL PRESENT in iOS** 
**Assign back to dev**
@pmigueld @danicaerediano @Anushree09-N @kyanthony @rakhimosip @Sujithbn 

**To Reproduce**
Steps to reproduce the behavior:

1. Share an ID
2. **See error** on `Tanggapin ang kahilingan at piliin ang ID` and `Tanggapin anf kahilingan at magpatunay` button
3. Select an ID and clicking on either `Tanggapin ang kahilingan at piliin ang ID` or `Tanggapin anf kahilingan at magpatunay`
4. **See error**


**Test devices:**
iPhone SE - iOS 15.4
iPhone 11 - iOS 16.1.1

**Screens
![IMG_3136](https://user-images.githubusercontent.com/102940764/205811230-7bed948e-1fc3-4ef1-86cd-077e0e3bd332.jpg)
hot**
![IMG_3135](https://user-images.githubusercontent.com/102940764/205811243-102872e2-d8b9-4846-9e76-38839115fce9.jpg)

**Comment by Anushree09-N** [comment]
Verified on:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (4) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa5.mosip.net

@jannahadlaon we still see issue with error messages 

![image](https://user-images.githubusercontent.com/79500509/208084466-3b9ca1b0-ab5a-445e-b188-fa5e7db8e686.png)
![image](https://user-images.githubusercontent.com/79500509/208084490-f925e14b-ab44-47bf-b32f-32907ceb7a48.png)
![image](https://user-images.githubusercontent.com/79500509/208084512-fe84c330-9ca2-46d4-a89b-935fcf49a345.png)
![image](https://user-images.githubusercontent.com/79500509/208085335-d35c016b-8991-4933-a67a-3ed75b5ea0dc.png)
![image](https://user-images.githubusercontent.com/79500509/208085368-db65ed22-0aac-4b48-b5ea-1089cd7ca1df.png)

VC receiving and sharing time in history tab

![image](https://user-images.githubusercontent.com/79500509/208084718-afbd1cfd-1158-4826-868c-715f513497c4.png)

Credits and legal page in profile section

![image](https://user-images.githubusercontent.com/79500509/208085520-4e0cda01-58d5-4e8b-9173-dfe495bf27cc.png)

**Comment by Anil-kumar-Majji** [comment]
@Anushree09-N  @santhoshsunder The above issues were solved by adjusting all related language files in locals. I raised the respective PR and sent it. Recheck once the code was merged.

**Comment by Anushree09-N** [comment]
Verified in:

Device: iPhone 8 & iPhone 11
OS: 16.0.2 (20A380), 15.6.1
Inji app version: 0.4.1 (10) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Able to replicate issue 

![image](https://user-images.githubusercontent.com/79500509/212685970-659526c0-12bd-4552-8fe9-e4ac9fc73754.png)

![image](https://user-images.githubusercontent.com/79500509/212686012-7c662e19-1041-477a-95bd-9c541311f03b.png)

![image](https://user-images.githubusercontent.com/79500509/212686041-9a56da9e-9210-4706-972f-f92cfba89e53.png)

![image](https://user-images.githubusercontent.com/79500509/212686073-5043467b-6991-4f88-a837-11ac45432b9d.png)

![image](https://user-images.githubusercontent.com/79500509/212686143-bdbffeee-a2db-4ee6-8184-9405246e7f47.png)

![image](https://user-images.githubusercontent.com/79500509/212686178-bb454ca8-7fd0-49cf-831c-72fd3cd86fd6.png)

![image](https://user-images.githubusercontent.com/79500509/212686222-9e46f04f-f366-4ae1-9a6f-daaa194ae507.png)

![image](https://user-images.githubusercontent.com/79500509/212686257-39d5c75e-781e-45a4-9ef3-522cfd9e4b0d.png)

**Comment by Anil-kumar-Majji** [comment]
@Anushree09-N UIN, VID, MOSIP, and ID words like these are prefered to translate. I already mentioned in the above comment that the translating errors related to the backend and Markdown language were not done.

**Comment by rakhimosip** [comment]
@Anil-kumar-Majji leave terms like ID, VID, UIN, and MOSIP I still see some more text that appears in English. We can address those.

**Comment by rakhimosip** [comment]
@Anushree09-N @Anil-kumar-Majji regarding the translation of ID, VID, UIN, and MOSIP labels -> I did some research and in conclusion, I feel we can go ahead and add them to locale files. 
If a country wants to keep a mix of local language labels + eng versions for these (ID, VID, UIN) they can go ahead and add English labels in their language's locale file.

**Comment by Anil-kumar-Majji** [comment]
@Anushree09-N The reopened above language switching issue was resolved by modifying locals and machine files. Respective PR(#494 ) raised and submitted.

**Comment by Pragya279** [comment]
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26836
