### ISSUE TITLE
When Residents request VC with VID the UIN label should be changed to VID

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#94]
**Describe the bug**
When Residents request VC with VID the UIN label should be changed to VID

**To Reproduce**
1. Get VC by entering VID
2. View the generated VC

**Current behavior**
Even though the Resident request the VC with VID still we see UIN label while viewing VC in My VID's Section

**Expected behavior**
UIN label should be changed to VID

**Screenshots**
![mobapp](https://user-images.githubusercontent.com/79500509/188402171-3d325414-6afe-44b9-9fed-7dd988c0388f.png)

**Smartphone (please complete the following information):**

- Device: Andriod
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**
https://github.com/mosip/inji/actions/runs/2926569813 apk 
Environment : qa5.mosip.net

**Comment by srikanth716** [comment]
Fixed and PR raised, Waiting for code review by @gsasikumar sir, https://github.com/mosip/inji/pull/152

**Comment by rakhimosip** [comment]
@Anushree09-N after https://mosip.atlassian.net/browse/MOSIP-23106, it is possible to support a VID attribute in policy as well. The label in the app UI is determined by the values returned in the VC based on the policy and not by what the user enters as input.

**Comment by santhoshsunder** [comment]
Verified this issue in QA5 env, the issue is still happening, able see UIN details still in the VC which is downloaded by VID, iam attaching the screenshot bellow, and reopening this bug again 

**Screenshot:**
![image](https://user-images.githubusercontent.com/102220709/208158244-733e8c57-3401-45b5-a0b0-6b17207bad81.png)

**Smartphone:**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net
- APP link; https://mosip.atlassian.net/browse/DSD-1816

**Comment by rakhimosip** [comment]
@santhoshsunder please update the bug description as per our discussion.
CC @srikanth716 
![image](https://user-images.githubusercontent.com/86289097/208403965-d288e5d7-1833-4ec2-8009-54bab4566be5.png)

**Comment by srikanth716** [comment]
Fixed the issue with pr(https://github.com/mosip/inji/pull/389). Based on the policy if the policy returned UIN it will show UIN as a header or If the policy returns the VID then it will show VID but if the Policy returned both UIN and VID then it will take UIN as a priority and show UIN as the header

**Comment by Raginikrishnamurthy** [comment]
@Sujithbn We can verify this once we have the VID support implemented, hence assigning to you.

**Comment by santhoshsunder** [comment]
verified as fixed in the build with commit id in the below screenshot. 
https://drive.google.com/file/d/15uWjasH2tRj0qCau8Ljj8YFEoSXi6mfd/view?usp=drivesdk
